// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtur60xWhKNNVEgNF2oOas020YXDnDREs',
    appId: '1:121465123098:web:0d59e4013835e0f5ebfca3',
    messagingSenderId: '121465123098',
    projectId: 'microcredential-b844f',
    authDomain: 'microcredential-b844f.firebaseapp.com',
    storageBucket: 'microcredential-b844f.appspot.com',
    measurementId: 'G-MT7XFP922M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9nVAs7Vjan60O22yCilKK22US_lSlF7E',
    appId: '1:121465123098:android:237937f6c14c1208ebfca3',
    messagingSenderId: '121465123098',
    projectId: 'microcredential-b844f',
    storageBucket: 'microcredential-b844f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuhTv3LQtZuvxaOtrg63mCMa0AyS1Pv8',
    appId: '1:121465123098:ios:0fa37a39b2957a90ebfca3',
    messagingSenderId: '121465123098',
    projectId: 'microcredential-b844f',
    storageBucket: 'microcredential-b844f.appspot.com',
    iosBundleId: 'com.example.microcredential',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZuhTv3LQtZuvxaOtrg63mCMa0AyS1Pv8',
    appId: '1:121465123098:ios:0fa37a39b2957a90ebfca3',
    messagingSenderId: '121465123098',
    projectId: 'microcredential-b844f',
    storageBucket: 'microcredential-b844f.appspot.com',
    iosBundleId: 'com.example.microcredential',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtur60xWhKNNVEgNF2oOas020YXDnDREs',
    appId: '1:121465123098:web:a05bdad5add67874ebfca3',
    messagingSenderId: '121465123098',
    projectId: 'microcredential-b844f',
    authDomain: 'microcredential-b844f.firebaseapp.com',
    storageBucket: 'microcredential-b844f.appspot.com',
    measurementId: 'G-SPVJB23QWF',
  );
}
